<Project>
  <ItemGroup Condition="'$(GarglkSdkLibDir)' != ''">
    <AdditionalNativeLibraryDirectories Include="$(GarglkSdkLibDir)" />
    <AdditionalNativeLibraryDirectories Include="$(GarglkUcrtLibDir)" />
    <AdditionalNativeLibraryDirectories Include="$(GarglkCrtLibDir)" />
  </ItemGroup>
</Project>
