name: AppImage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amd64/ubuntu:22.04
      # So that fuse works inside the container (needed to run AppImages.)
      options: --privileged

    steps:
      - run: apt update

      - name: Install deps
        run: DEBIAN_FRONTEND=noninteractive apt install -y
          build-essential
          clang
          cmake
          file
          fuse
          git
          grep
          libfmt-dev
          libfontconfig1-dev
          libfreetype-dev
          libjpeg-turbo8-dev
          libsdl2-mixer-dev
          libspeechd-dev
          libturbojpeg0-dev
          patchelf
          qt6-base-dev
          qt6-base-dev-tools
          wget

      - uses: actions/checkout@v4

      - name: Build AppImage
        run: |
          echo $(date +"%Y%m%d").$(echo $GITHUB_SHA | cut -b 1-7) > VERSION
          ./gargoyle-appimage.sh

      - name: Upload AppImage
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Gargoyle-x86_64.AppImage
          path: Gargoyle-x86_64.AppImage
