name: macOS (Qt)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install fluid-synth fmt libopenmpt libsndfile libvorbis mpg123 pkg-config qt6 libpng jpeg

      - name: Build (Qt)
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -DINTERFACE=QT -DSOUND=QT -DCMAKE_FIND_FRAMEWORK=LAST
          make -j`sysctl -n hw.ncpu`
