name: macOS (DMG)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install x86_64 brew
        run: /usr/bin/arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install packages
        run: PATH=/usr/local/bin:$PATH brew install fmt jpeg-turbo pkg-config sdl2 sdl2_mixer

      - name: Build
        run: |
          echo $(date +"%Y%m%d").$(echo $GITHUB_SHA | cut -b 1-7) > VERSION
          bash gargoyle_osx.sh -c

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gargoyle.dmg
          path: gargoyle*.dmg
